// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwV3MwHa3QTgcBTjPFIyVddYKp62-OLpY',
    appId: '1:92893406458:web:b1f9edb2bad41f16129543',
    messagingSenderId: '92893406458',
    projectId: 'cu-smart-home',
    authDomain: 'cu-smart-home.firebaseapp.com',
    databaseURL: 'https://cu-smart-home-default-rtdb.firebaseio.com',
    storageBucket: 'cu-smart-home.appspot.com',
    measurementId: 'G-XL0DY5YKW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnDNmxd8N_U9h3xfHF_txB4nWo6apJ9es',
    appId: '1:92893406458:android:8983aa9f57a8592b129543',
    messagingSenderId: '92893406458',
    projectId: 'cu-smart-home',
    databaseURL: 'https://cu-smart-home-default-rtdb.firebaseio.com',
    storageBucket: 'cu-smart-home.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABabp8WsU7rCFALhzhv90IRKLZUXhqXHQ',
    appId: '1:92893406458:ios:bccced0a7808d1ba129543',
    messagingSenderId: '92893406458',
    projectId: 'cu-smart-home',
    databaseURL: 'https://cu-smart-home-default-rtdb.firebaseio.com',
    storageBucket: 'cu-smart-home.appspot.com',
    iosBundleId: 'com.example.cuSmartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABabp8WsU7rCFALhzhv90IRKLZUXhqXHQ',
    appId: '1:92893406458:ios:1f67979048b4729b129543',
    messagingSenderId: '92893406458',
    projectId: 'cu-smart-home',
    databaseURL: 'https://cu-smart-home-default-rtdb.firebaseio.com',
    storageBucket: 'cu-smart-home.appspot.com',
    iosBundleId: 'com.example.cuSmartHome.RunnerTests',
  );
}
